server:
  port: 8081

---
spring:
  profiles:
    active: dev


---
spring:
  config:
    activate:
      on-profile: dev
server:
  port: 1150
dynamo:
  secretKey: TtP3D6rhlmRehd+3IvuXwijZNpOX0naDjhTDDTR0
  accessKey: AKIAQFI4U3I63F3I47VE
  serviceEndpoint: dynamodb.ap-southeast-1.amazonaws.com
  signingRegion: ap-southeast-1

---
spring:
  config:
    activate:
      on-profile: uat
server:
  port: 1152
dynamo:
  secretKey: TtP3D6rhlmRehd+3IvuXwijZNpOX0naDjhTDDTR0
  accessKey: AKIAQFI4U3I63F3I47VE
  serviceEndpoint: dynamodb.ap-southeast-1.amazonaws.com
  signingRegion: ap-southeast-1
---
spring:
  config:
    activate:
      on-profile: prod
server:
  port: 5000